---
title: "p8105_hw2_cjh2248"
output: github_document
date: "2024-09-28"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
```

```{r}
transit_df = 
  read_csv("data/nyc_transit.csv", na = c("NA","","."))
  transit_df = janitor::clean_names(transit_df)
```

```{r}
select(transit_df, line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada) |>
  mutate(entry = case_match(entry, 
                            "YES" ~ TRUE, 
                            "NO" ~ FALSE, 
                            .default = NA))

select(transit_df, -division, -exit_only, -staffing, -staff_hours, -ada_notes, -free_crossover, -north_south_street, -east_west_street, -corner, -entrance_latitude, -entrance_longitude, -station_location,-entrance_location)
```
```{r}
distinct_stations <- transit_df %>%
  distinct(station_name, line) %>%
  nrow()
```

```{r}
print(distinct_stations)
```
```{r}
ada_stations_count <- transit_df %>%
  filter(ada == TRUE) %>%
  nrow()

```
```{r}
print(ada_stations_count)
```








